class Transform;
class Scene;
class Vector2;
class Quaternion;
class Matrix4x4;
class Object;
class Component;
class Behaviour;
class MonoBehaviour;
class GameObject;
class SceneManager;
class Texture;
class Camera;
class Image;
class Text;
class BoxCollider2D;
class ProjectSettings;
void LoadScene(Scene* scene, int nb);
GameObject* FindWithName(unsigned char* name,GameObject* gameObject);
class AllFightGolem;
class BallGolem;
class ChangeSceneTrigger;
class Curseur;
class Dialogue1;
class GameManagerCible;
class MainMenu;
class PlayerController;
class RoomCible;
