class Transform;
class Scene;
class Vector2;
class Quaternion;
class Matrix4x4;
class Object;
class Component;
class Behaviour;
class MonoBehaviour;
class GameObject;
class SceneManager;
class Texture;
class Camera;
class Image;
class Text;
void LoadScene(Scene* scene, int nb);
GameObject* FindWithName(unsigned char* name,GameObject* gameObject);
class PlayerController;
